- name: Install essential packages
  yum:
    name:
      - expect
      - git
      - vim-minimal
    state: present
    update_cache: yes
    enablerepo: epel
  register: yum_res
  retries: 10
  until: yum_res is succeeded
  delay: 5
