- name: Install HTTPD packages
  yum:
    name:
      - httpd
    state: present
    update_cache: yes
    enablerepo: epel
  register: yum_res
  retries: 10
  until: yum_res is succeeded
  delay: 5

- name: Deploy XDMoD preconfigured conf to HTTPD
  template: src=xdmod.conf.j2 dest=/etc/httpd/conf.d/xdmod.conf
            owner=root group=root mode=0644
